### ISSUE TITLE
format problem

### ISSUE THREAD

**Issue by GithubCHN** [BrainTech/svarog#1]
Svarog processes the SignalML format data. But mine are *.csv, *.dat. it's a problem to use the Svarog!
Have any solutition? More than 10GB data are waiting!

**Comment by develancer** [comment]
Svarog can read raw binary multichannel data. For example, with 3-channel (x, y, z) data, the binary file should consist of interleaved samples:

```
x[0], y[0], z[0], x[1], y[1], z[1], x[2], y[2], z[2] …
```

and for all subsequent samples analogically. Each sample should be encoded as IEEE floating point value. Details (32-bit or 64-bit, little- or big-endian) should be selected when opening the binary file in Svarog.

All you have to do is to convert your text files into “raw” binary format.
