### ISSUE TITLE
MP decomposition

### ISSUE THREAD

**Issue by mjpietrzak** [BrainTech/svarog#2]
MP decomposition zwraca poniższy błąd. Pomogło dodanie linku symbolicznego "/usr/bin/mp5" do "/usr/lib/svarog-1.1.5/mp/linux/mp5-amd64", ale pierwotny zamysł był chyba inny.

message: java.io.IOException: Cannot run program "mp5" (in directory "/home/marcin/.svarog/44e50dc8c7c14b98"): error=2, Nie ma takiego pliku ani katalogu
class org.signalml.method.ComputationException
java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
org.signalml.method.mp5.MP5LocalProcessController.executeProcess(MP5LocalProcessController.java:58)
org.signalml.method.mp5.MP5LocalProcessExecutor.execute(MP5LocalProcessExecutor.java:141)
org.signalml.method.mp5.MP5Method.doComputation(MP5Method.java:153)
org.signalml.method.AbstractMethod.compute(AbstractMethod.java:33)
org.signalml.task.LocalTask.run(LocalTask.java:547)
org.signalml.task.LocalTask.doIfPossible(LocalTask.java:322)
org.signalml.app.task.ApplicationTaskWorker.doInBackground(ApplicationTaskWorker.java:69)
org.signalml.app.task.ApplicationTaskWorker.doInBackground(ApplicationTaskWorker.java:26)
javax.swing.SwingWorker$1.call(SwingWorker.java:296)
java.util.concurrent.FutureTask.run(FutureTask.java:262)
javax.swing.SwingWorker.run(SwingWorker.java:335)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:745)

**Comment by develancer** [comment]
To rozwiązanie działa, ponieważ ze względów historycznych Svarog domyślnie poszukuje programu „mp5” w ścieżce ($PATH). Bardziej uniwersalnym rozwiązaniem jest wskazanie ścieżki do binarnej implementacji MP (mp5 lub empi) w pozycji Edit → Preferences… → Tools → Add local.
